/*
 * This source file was generated by the Gradle 'init' task
 */

package aula;

import aula.Models.Cliente;
import aula.Models.Conta;
import aula.Models.Historico;

import java.util.ArrayList;
import java.util.Scanner;

public class Aula {

    static Scanner input = new Scanner(System.in);
    static ArrayList<Conta> contasBancarias;
    static ArrayList<Cliente> clientes;
    static ArrayList<Historico> historico;

    public static void main(String[] args) {
        contasBancarias = new ArrayList<Conta>();
        clientes = new ArrayList<Cliente>();
        historico = new ArrayList<Historico>();
        operacoesBancarias();
    }


    public static void operacoesBancarias() {

        System.out.println("-------------------------------------------------------------------");
        System.out.println("-------------Bem vindos a nossa Agencia KAlleb Banck---------------");
        System.out.println("-------------------------------------------------------------------");
        System.out.println("       ***** Selecione uma operacao que deseja realizar *****");
        System.out.println("-------------------------------------------------------------------");
        System.out.println("|   Opção 1 - Criar conta   |");
        System.out.println("|   Opção 2 - Depositar     |");
        System.out.println("|   Opção 3 - Sacar         |");
        System.out.println("|   Opção 4 - Transferir    |");
        System.out.println("|   Opção 5 - Listar contas |");
        System.out.println("|   Opção 6 - Histórico     |");
        System.out.println("|   Opção 7 - Sair          |");

        int operacao = input.nextInt();

        switch (operacao) {

            case 1:
                criarConta();
                break;

            case 2:
                depositar();
                break;

            case 3:
                sacar();
                break;
            
            case 4:
                transferir();
                break;

            case 5:
                listarContas();
                break;

            case 6:
                listarHistorico();
                break;

            case 7:
                System.out.println("Obrigado por utilizar nosso banco!");
                return;

            default:
                System.out.println("Operação inválida.");
                break;
        }

            // Depois do switch, pergunte se quer continuar
            ContinuarOperacoes();

    }

    public static void ContinuarOperacoes() {
        System.out.println("Deseja realizar outra operação? (S/N)");
        String resposta = input.next();

        if (resposta.equalsIgnoreCase("S")) {
            operacoesBancarias();
        } else {
            System.out.println("Obrigado por utilizar nosso banco!");
            System.exit(0);
        }
    }

    private static void transferir() {
        System.out.println("Qual Seu CPF: ");
        String cpf = input.next();

        System.out.println("Qual a sua conta que deseja transferir: ");
        int idConta = input.nextInt();

        System.out.println("para qual conta que deseja Tranferir: ");
        int idContaTransferir = input.nextInt();

        System.out.println("Qual o valor da transferencia: ");
        double valorTransferencia = input.nextDouble();

        Cliente cliente = BuscarCliente(cpf);
        Conta contaOrigem = BuscarConta(idConta);
        Conta contaDestino = BuscarConta(idContaTransferir);

        if (cliente == null) {
            System.out.println("Cliente não encontrado.");
            return;
        }

        if (contaOrigem == null) {
            System.out.println("Conta de origem não encontrada.");
            return;
        }

        if (contaDestino == null) {
            System.out.println("Conta de destino não encontrada.");
            return;
        }


        if (!contaOrigem.getCliente().getCpf().equals(cpf)) {
            System.out.println("O CPF informado não corresponde ao cliente da conta de origem.");
            return;
        }

        if (contaOrigem.getSaldo() < valorTransferencia) {
            System.out.println("Saldo insuficiente para realizar a transferência.");
            return;
        } else {
            contaOrigem.transferir(contaDestino, valorTransferencia);
            registrarHistorico("TRANSFERENCIA", valorTransferencia, contaOrigem, contaDestino);
            System.out.println("Transferência realizada com sucesso! Novo saldo da conta de origem: " + contaOrigem.getSaldo());
        }
        

    }


    private static void sacar() {
        
        System.out.println("Qual Seu CPF: ");
        String cpf = input.next();

        System.out.println("Qual o ID da conta que deseja sacar: ");
        int idConta = input.nextInt();

        System.out.println("Qual o valor do saque: ");
        double valorSaque = input.nextDouble();

        Cliente cliente = BuscarCliente(cpf);
        Conta conta = BuscarConta(idConta);

        if(cliente == null) {
            System.out.println("Cliente não encontrado.");
            return;
        }

        if (conta == null) {
            System.out.println("Conta não encontrada.");
            return;
        }

        if (!conta.getCliente().getCpf().equals(cpf)) {
            System.out.println("O CPF informado não corresponde ao cliente da conta.");
            return;
        }

        if (conta.getSaldo() < valorSaque) {
            System.out.println("Saldo insuficiente para realizar o saque.");
            return;
        } else {
            conta.sacar(valorSaque);
            registrarHistorico("SAQUE", valorSaque, conta, null);
            System.out.println("Saque realizado com sucesso! Novo saldo: " + conta.getSaldo());
        }

    }

    private static void depositar() {
        System.out.println("Qual Seu CPF: ");
        String cpf = input.next();

        System.out.println("Qual o ID da conta que deseja depositar: ");
        int idConta = input.nextInt();


        Cliente cliente = BuscarCliente(cpf);
        Conta conta = BuscarConta(idConta);

        if(cliente == null) {
            System.out.println("Cliente não encontrado.");
            return;
        }

        if (conta == null) {
            System.out.println("Conta não encontrada.");
            return;
        }

        if (!conta.getCliente().getCpf().equals(cpf)) {
            System.out.println("O CPF informado não corresponde ao cliente da conta.");
            return;
        }

        System.out.println("Digite o valor do depósito: ");
        double valorDeposito = input.nextDouble();
        conta.depositar(valorDeposito);
        registrarHistorico("DEPOSITO", valorDeposito, conta, null);
        System.out.println("Depósito realizado com sucesso! Novo saldo: " + conta.getSaldo());
      }

    private static void registrarHistorico(String tipo, double valor, Conta conta, Conta contaDestino) {
        String id = String.valueOf(historico.size() + 1);
        String contaId = String.valueOf(conta.getId());
        String contaDestinoId = contaDestino == null ? null : String.valueOf(contaDestino.getId());
        historico.add(new Historico(id, tipo, valor, contaId, contaDestinoId));
    }

    private static void listarHistorico() {
        if (historico.isEmpty()) {
            System.out.println("Nenhuma transação registrada.");
            return;
        }

        System.out.println("\n---------------- HISTÓRICO DE TRANSAÇÕES ----------------");
        for (Historico transacao : historico) {
            String destino = transacao.getContaDestinoId() == null
                    ? "-"
                    : transacao.getContaDestinoId();
            System.out.println("ID: " + transacao.getId()
                    + " | Tipo: " + transacao.getTipo()
                    + " | Valor: " + transacao.getValor()
                    + " | Conta: " + transacao.getContaId()
                    + " | Destino: " + destino);
        }
    }

    private static void listarContas() {
        if (contasBancarias.isEmpty()) {
            System.out.println("Nenhuma conta cadastrada.");
            return;
        }

        System.out.println("\n---------------- CONTAS BANCÁRIAS ----------------");
        for (Conta conta : contasBancarias) {
            System.out.println("ID: " + conta.getId()
                    + " | Titular: " + conta.getCliente().getNome()
                    + " | Saldo: " + conta.getSaldo());
        }
    }



   public static Conta BuscarConta(int id) {
        for (Conta conta : contasBancarias) {
            if (conta.getId() == id) {
                return conta;
            }
        }
        return null;
    }




    

    private static void criarConta() {

        System.out.println("\nNome: ");
        String nome = input.next();

        System.out.println("\nE-mail: ");
        String email = input.next();

        System.out.println("\nCPF: ");
        String cpf = input.next();


        // com as informações ja consigo criar um cliente ou buscar um cliente existente, caso o mesmo já tenha uma conta no banco
        Cliente cliente = BuscarCliente(cpf);
        
        // se nao existir eu busco ele
        if (cliente == null) {
            cliente = new Cliente(nome,email,cpf);
            clientes.add(cliente);
        } 


        // se ele ja tiver uma conta, nao posso criar outra
        if (contasBancarias.isEmpty()){
            Conta novaConta = new Conta(1, 0.0, cliente);
            contasBancarias.add(novaConta);
            System.out.println("Conta criada com sucesso! ID da conta: " + novaConta.getId());
            
        } else {

            for (Conta contasBancaria : contasBancarias) {
                if (contasBancaria.getCliente().getCpf().equals(cpf)) {
                    System.out.println("O cliente já possui uma conta.");
                    return;
                }
            }

            //  faço um sort para pegar o id da ultima conta criada e somar +1 para criar a nova conta
            contasBancarias.sort((c1, c2) -> Integer.compare(c1.getId(), c2.getId()));

            // pego o ultimo id da lista de contas e somo +1 para criar a nova conta
            int proximoId = contasBancarias.isEmpty() ? 1 : contasBancarias.get(contasBancarias.size() - 1).getId() + 1;

            // adciono essa nova conta na lista de contas
            Conta novaConta = new Conta(proximoId, 0.0, cliente);
            contasBancarias.add(novaConta);


            System.out.println("Conta criada com sucesso! ID da conta: " + novaConta.getId());

        }
        
    }
        


    public static Cliente BuscarCliente(String cpf) {

        for (Cliente cliente : clientes) {
            if (cliente.getCpf().equals(cpf)) {
                return cliente;
            }
        }
        return null;
    }

}

